### ISSUE TITLE
[Challenger-submission] #1

### ISSUE THREAD

**Issue by haholm** [Hampfh/Hampfh#28]
```lua
-- IMPORTANT: By submitting this code you agree that your 
-- github username will be saved and shown on this profile

-- All Lua code within this code block will be executed
-- Code outside the onTurn function will only run once
-- If you want any persistent state between turns it might 
-- therefore be good to declare it here

-- This program will just go upwards

-- comments are overrated

function onTurn(context)
    local playerX = context.player.X
    local playerY = context.player.Y
    
    if playerY < 3 and playerY > 0 and STD__GET_TILE(context, playerX, playerY - 1) == 0 then
        return tostring(playerX - playerY + 1) .. " " .. tostring(playerY - 1) .. " " .. tostring(playerX - playerY + 2) .. " " .. tostring(playerY - 1)
    end

    if not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY + 1) and STD__GET_TILE(context, playerX, playerY + 1) == 3 and not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY + 2) and STD__GET_TILE(context, playerX, playerY + 2) == 3 then
        return "1"
    end

    return "0"
end

function onJump(context)
    return "0"
end

```

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> User: haholm<br>Script-id: f13c68b7-694e-4b87-941d-fb587c2b6519<br>Thanks for submitting!<br>Your code is being processed...

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [0f152710-dcbb-49df-8566-d82afaa2fd67](https://github.com/hampfh/hampfh/issues/27)
**Error:**
runtime error: [string "?"]:18: attempt to compare nil with number
stack traceback:
	[C]: in metamethod 'lt'
	[string "?"]:18: in function 'onTurn'
	[string "?"]:1: in main chunk

This submission has been disqualififed<br>[ERROR] Opponent: [bd8d0156-bd11-4ff9-b13c-b222d4abefa6](https://github.com/hampfh/hampfh/issues/26)
**Error:**
runtime error: [string "?"]:18: attempt to compare nil with number
stack traceback:
	[C]: in metamethod 'lt'
	[string "?"]:18: in function 'onTurn'
	[string "?"]:1: in main chunk

This submission has been disqualififed<br>
