### ISSUE TITLE
[Challenger-submission] #1.1

### ISSUE THREAD

**Issue by haholm** [Hampfh/Hampfh#29]
-- IMPORTANT: By submitting this code you agree that your 
-- github username will be saved and shown on this profile

-- All Lua code within this code block will be executed
-- Code outside the onTurn function will only run once
-- If you want any persistent state between turns it might 
-- therefore be good to declare it here

-- This program will just go upwards

-- comments are overrated

function onTurn(context)
    local playerX = context.player.x
    local playerY = context.player.y
    
    if playerY < 3 and playerY > 0 and STD__GET_TILE(context, playerX, playerY - 1) == 0 then
        return tostring(playerX - playerY + 1) .. " " .. tostring(playerY - 1) .. " " .. tostring(playerX - playerY + 2) .. " " .. tostring(playerY - 1)
    end

    if not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY + 1) and STD__GET_TILE(context, playerX, playerY + 1) == 3 and not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY + 2) and STD__GET_TILE(context, playerX, playerY + 2) == 3 then
        return "1"
    end

    return "0"
end

function onJump(context)
    return "0"
end

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> Could not parse code block, please check the documentation on how to format your submissions
