### ISSUE TITLE
[Challenger-submission] #1.2

### ISSUE THREAD

**Issue by haholm** [Hampfh/Hampfh#30]
```lua
-- IMPORTANT: By submitting this code you agree that your 
-- github username will be saved and shown on this profile

-- All Lua code within this code block will be executed
-- Code outside the onTurn function will only run once
-- If you want any persistent state between turns it might 
-- therefore be good to declare it here

-- This program will just go upwards

-- comments are overrated

function onTurn(context)
    local playerX = context.player.x
    local playerY = context.player.y
    
    if playerY < 3 and playerY > 0 and STD__GET_TILE(context, playerX, playerY - 1) == 0 then
        return tostring(playerX - playerY + 1) .. " " .. tostring(playerY - 1) .. " " .. tostring(playerX - playerY + 2) .. " " .. tostring(playerY - 1)
    end

    if not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY + 1) and STD__GET_TILE(context, playerX, playerY + 1) == 3 and not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY + 2) and STD__GET_TILE(context, playerX, playerY + 2) == 3 then
        return "1"
    end

    return "0"
end

function onJump(context)
    return "0"
end

```

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> User: haholm<br>Script-id: 2b04c102-556f-4522-b0b4-77f531c2f46d<br>Thanks for submitting!<br>Your code is being processed...

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [0f152710-dcbb-49df-8566-d82afaa2fd67](https://github.com/hampfh/hampfh/issues/27)
**Error:**
Invalid return format, expected 4 values, got: [3 1 4 1]


[Match](../blob/live/data/matches/2d4690ad-a94b-4ce1-9dfb-6297aeca18f6.md)<br>[ERROR] Opponent: [bd8d0156-bd11-4ff9-b13c-b222d4abefa6](https://github.com/hampfh/hampfh/issues/26)
**Error:**
Invalid return format, expected 4 values, got: [3 1 4 1]


[Match](../blob/live/data/matches/aeddf41f-88d0-440d-a52d-e393cb40e235.md)<br>

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [16754832-98d7-4d61-9c5c-b29eabd5e3ec](https://github.com/hampfh/hampfh/issues/31)
**Error:**
Invalid return format, expected 4 values, got: [4 1 5 1]


[Match](../blob/live/data/matches/ec5a6898-de84-4ce1-a241-64d717471efe.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [SUCCESS] Opponent: [817b32b1-2977-4d34-b56e-133454c949f1](https://github.com/hampfh/hampfh/issues/33)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [e3a92717-b5e7-4112-a529-cf7183454921](https://github.com/hampfh/hampfh/issues/34)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/af30d814-a695-4e61-84db-f653f4870393.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [966be351-a717-4c74-9190-807e0a407fcb](https://github.com/hampfh/hampfh/issues/35)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/f8629630-7cc7-4849-b413-35565968bf0b.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [f95962fb-c0d5-405f-ad89-d78a094805be](https://github.com/hampfh/hampfh/issues/36)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/69afaf1a-ce7c-4624-9318-61ab4d15f6c7.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [5f430493-31ed-4439-87a7-782604564e4c](https://github.com/hampfh/hampfh/issues/37)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/c5bffb11-0f85-4348-83ce-71a42c9e5564.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [f23dbe45-22fd-4409-9943-739651279bfe](https://github.com/hampfh/hampfh/issues/38)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/8d7030b4-d057-4aed-80da-e83344333af9.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [79c17c11-48a4-424e-9a56-759309ab4b02](https://github.com/hampfh/hampfh/issues/39)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/d31f3376-185d-4bd8-9b53-50ab36f042fe.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [cba2eedc-eaf0-4b15-9b4e-bf924cc7474e](https://github.com/hampfh/hampfh/issues/40)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/8604b8c5-307d-42c3-ba38-bdf766b68346.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [f1cbfd73-176b-46ff-bd02-38a9a5f43e40](https://github.com/hampfh/hampfh/issues/41)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/e57b0d64-8576-4dcf-a24b-3105dbb4c215.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [5375c5c9-002a-4b10-853a-d5e42ad97dad](https://github.com/hampfh/hampfh/issues/42)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/67e54869-1455-43e2-89f1-847d0524a258.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [c1470855-52fd-4e2f-81a9-b59ce29945ff](https://github.com/hampfh/hampfh/issues/43)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/456c7035-0519-4bbe-b02e-911aecc9578e.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [d94f9c1e-8d5d-4a97-8c3f-e81f102a1f82](https://github.com/hampfh/hampfh/issues/44)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/4d209295-544c-44d6-b0ca-f5d9c5d0c60c.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [661deec5-1967-4f0c-82de-69b3b01e47a1](https://github.com/hampfh/hampfh/issues/45)
**Error:**
Invalid move: Tile (4,7) is occupied


[Match](../blob/live/data/matches/ef56504d-b24b-4170-88e4-e13ad2c6ce3e.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [c0412c19-887b-4762-9fa9-d93aab383d83](https://github.com/hampfh/hampfh/issues/46)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/4b6e590a-efd4-478c-a1d7-fc6baa9991a4.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [39e70f81-7b24-4108-9cf0-f1e14f0f5066](https://github.com/hampfh/hampfh/issues/47)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/e60cba22-4fd0-463f-bc1f-ca60ade88dd1.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [1ad25e74-17a9-41e4-a042-47a66648c382](https://github.com/hampfh/hampfh/issues/48)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/fcc2281b-38b2-4334-891b-189736d3aa54.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [d841e224-57bb-4c8c-9743-b7acf54f8d0c](https://github.com/hampfh/hampfh/issues/49)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/188c0ff3-afec-40b1-8318-50c1389643e8.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [e62c6a3e-3123-4041-ab24-05382f85f23c](https://github.com/hampfh/hampfh/issues/51)
**Error:**
Invalid move: Tile (4,7) is occupied


[Match](../blob/live/data/matches/1c6d7aee-0e94-4e7e-be47-0a5c9e823ea6.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [f4e7e93d-fc25-4b64-9068-39506c1d7e9e](https://github.com/hampfh/hampfh/issues/52)
**Error:**
Invalid move: Tile (4,7) is occupied


[Match](../blob/live/data/matches/622bc40d-b61a-4c5c-854d-81a6f7b77aef.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [367e1c4b-ff88-40a8-a054-9718470fb7fd](https://github.com/hampfh/hampfh/issues/53)
**Error:**
Invalid return format, expected 4 values, got: [4 1 5 1]


[Match](../blob/live/data/matches/bc0e0781-3d0a-4813-b56a-f031aee5a6be.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [1da0638b-0912-4672-8237-4f5bf502c6b4](https://github.com/hampfh/hampfh/issues/55)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/b6d20ee7-f485-4711-9549-48f065d498e2.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [adbd08b3-8504-4b72-83ae-23b843313692](https://github.com/hampfh/hampfh/issues/56)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/b196914c-9936-4f7b-bf87-d26dde655195.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [fe128b4c-b947-4420-990a-7658f8c2dc48](https://github.com/hampfh/hampfh/issues/61)
**Error:**
Invalid return format, expected 4 values, got: [3 1 4 1]


[Match](../blob/live/data/matches/91601d12-880a-4043-a8ce-302196c321a1.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [e25da2fb-8bc8-4b19-b6af-69c5a64c6af9](https://github.com/hampfh/hampfh/issues/64)
**Error:**
Invalid move: Tile (4,7) is occupied


[Match](../blob/live/data/matches/feb44675-0d9f-460d-a455-618a54b9b670.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [6abd680d-558a-4d10-8a94-72ffccfa949c](https://github.com/hampfh/hampfh/issues/69)
**Error:**
Invalid move: Tile (4,8) is occupied


[Match](../blob/live/data/matches/37492080-61b8-41da-9ee9-0765e1d838fa.md)
