### ISSUE TITLE
[Challenger-submission]

### ISSUE THREAD

**Issue by haholm** [Hampfh/Hampfh#51]
```lua
-- comments are overrated

function onTurn(context)
    local playerX = context.player.x
    local playerY = context.player.y

    if playerY > 5 and playerY < 8 and STD__GET_TILE(context, playerX, playerY + 1) == 0 then
        return tostring(playerX + (playerY - 8) + 1) .. "," .. tostring(playerY + 1) .. "," .. tostring(playerX + (playerY - 8) + 2) .. "," .. tostring(playerY + 1)
    end

    if not STD__CHECK_OUT_OF_BOUNDS(playerX, playerY - 1) and STD__GET_TILE(context, playerX, playerY - 1) == 3 then
        return "1"
    end
    return "0"
end

function onJump(context)
    return "0"
end

```

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> User: haholm<br>Script-id: e62c6a3e-3123-4041-ab24-05382f85f23c<br>Thanks for submitting!<br>Your code is being processed...

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [SUCCESS] Opponent: [2b04c102-556f-4522-b0b4-77f531c2f46d](https://github.com/hampfh/hampfh/issues/30)
[Match](../blob/live/data/matches/1c6d7aee-0e94-4e7e-be47-0a5c9e823ea6.md)<br>[SUCCESS] Opponent: [16754832-98d7-4d61-9c5c-b29eabd5e3ec](https://github.com/hampfh/hampfh/issues/31)
[Match](../blob/live/data/matches/6627d853-d506-4ecb-b7a0-4b3c39ecbe55.md)<br>[SUCCESS] Opponent: [661deec5-1967-4f0c-82de-69b3b01e47a1](https://github.com/hampfh/hampfh/issues/45)
[Match](../blob/live/data/matches/9d39dcb2-0caa-4039-962f-ab40be15d278.md)<br>[ERROR] Opponent: [c0412c19-887b-4762-9fa9-d93aab383d83](https://github.com/hampfh/hampfh/issues/46)
**Error:**
Invalid wall placement at ((4,7),(5,7)), coordinates are either occupied or out of bounds


[Match](../blob/live/data/matches/23a0c5a0-808a-4b82-8f8a-b696d2bb35e8.md)<br>[ERROR] Opponent: [39e70f81-7b24-4108-9cf0-f1e14f0f5066](https://github.com/hampfh/hampfh/issues/47)
**Error:**
Invalid wall placement at ((4,7),(5,7)), coordinates are either occupied or out of bounds


[Match](../blob/live/data/matches/8aef829e-ce9f-466e-b9b4-dff5912b7eae.md)<br>[ERROR] Opponent: [1ad25e74-17a9-41e4-a042-47a66648c382](https://github.com/hampfh/hampfh/issues/48)
**Error:**
Invalid wall placement at ((4,7),(5,7)), coordinates are either occupied or out of bounds


[Match](../blob/live/data/matches/45baa743-e30e-48d4-b193-9bd0ebb11d1d.md)<br>[ERROR] Opponent: [d841e224-57bb-4c8c-9743-b7acf54f8d0c](https://github.com/hampfh/hampfh/issues/49)
**Error:**
Invalid wall placement at ((4,7),(5,7)), coordinates are either occupied or out of bounds


[Match](../blob/live/data/matches/a3611a9c-9010-4e51-9195-e4d99a2fc854.md)<br>[SUCCESS] Opponent: [bd8d0156-bd11-4ff9-b13c-b222d4abefa6](https://github.com/hampfh/hampfh/issues/26)
[Match](../blob/live/data/matches/784f82a1-be80-4441-95b2-29c5c7c89c33.md)<br>[WIN] Opponent: [0f152710-dcbb-49df-8566-d82afaa2fd67](https://github.com/hampfh/hampfh/issues/27) &#124; [Match](../blob/live/data/matches/1911c6a1-b678-46d9-8482-31fd0bdcbec3.md)<br>

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [f4e7e93d-fc25-4b64-9068-39506c1d7e9e](https://github.com/hampfh/hampfh/issues/52)
**Error:**
Invalid move: Tile (4,7) is occupied


[Match](../blob/live/data/matches/a3d1d830-84f8-47ea-8761-d4e889cc2919.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [SUCCESS] Opponent: [367e1c4b-ff88-40a8-a054-9718470fb7fd](https://github.com/hampfh/hampfh/issues/53)
[Match](../blob/live/data/matches/b5c61daa-f9a0-4d34-8bca-0e279316f797.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [1da0638b-0912-4672-8237-4f5bf502c6b4](https://github.com/hampfh/hampfh/issues/55)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/6a777294-0304-461b-9d88-0cc288230ef6.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [adbd08b3-8504-4b72-83ae-23b843313692](https://github.com/hampfh/hampfh/issues/56)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/8ef4b9d7-ef64-4194-9b27-3c687776d581.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [LOSS] Opponent: [fe128b4c-b947-4420-990a-7658f8c2dc48](https://github.com/hampfh/hampfh/issues/61) &#124; [Match](../blob/live/data/matches/ea247ded-07c1-4050-9b07-54edc83e6bc0.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [e25da2fb-8bc8-4b19-b6af-69c5a64c6af9](https://github.com/hampfh/hampfh/issues/64)
**Error:**
Invalid move: Tile is out of bounds (-1, 6)


[Match](../blob/live/data/matches/7331cffb-c300-44cb-be90-960bf8b2d33b.md)
