### ISSUE TITLE
Accidental bot

### ISSUE THREAD

**Issue by WilleMahMille** [Hampfh/Hampfh#53]
```lua
-- IMPORTANT: By submitting this code you agree that your 
-- github username will be saved and shown on this profile

-- All Lua code within this code block will be executed
-- Code outside the onTurn function will only run once
-- If you want any persistent state between turns it might 
-- therefore be good to declare it here

-- This program will just go upwards

function onTurn(context)
    -- This code will run on every turn

    -- context has the following structure
    -- { 
    --    player={x, y, wallCount}, 
    --    opponent={x, y, wallCount}, 
    --    board=[0,0,0,0....] 9x9 long (one-dimensional) list containing tiles
    -- }
    -- Valid tiles are: { 0: Empty, 1: Player_One, 2: Player_two, 3: Wall} 

    -- Valid return types are UP=0, RIGHT=1, DOWN=2, LEFT=3 and wall
    -- Example if we want to place a wall from (1,1) to (1,2) then we would
    -- return "1,1,1,2"
    return "0"
end

function onJump(context)
    -- Valid returns are 0, 1, 2, 3, for more details read the docs
    return "0"
end

```

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> User: WilleMahMille<br>Script-id: 367e1c4b-ff88-40a8-a054-9718470fb7fd<br>Thanks for submitting!<br>Your code is being processed...

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [SUCCESS] Opponent: [2b04c102-556f-4522-b0b4-77f531c2f46d](https://github.com/hampfh/hampfh/issues/30)
[Match](../blob/live/data/matches/bc0e0781-3d0a-4813-b56a-f031aee5a6be.md)<br>[LOSS] Opponent: [16754832-98d7-4d61-9c5c-b29eabd5e3ec](https://github.com/hampfh/hampfh/issues/31) &#124; [Match](../blob/live/data/matches/508666af-3218-440a-a269-46e15a983318.md)<br>[ERROR] Opponent: [661deec5-1967-4f0c-82de-69b3b01e47a1](https://github.com/hampfh/hampfh/issues/45)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/88ba0af4-c38f-48de-a4ce-a80261190b22.md)<br>[ERROR] Opponent: [c0412c19-887b-4762-9fa9-d93aab383d83](https://github.com/hampfh/hampfh/issues/46)
**Error:**
Invalid move: Tile (4,5) is occupied


[Match](../blob/live/data/matches/ff61bdce-d594-4140-9be8-87f8bf4e7e8d.md)<br>[ERROR] Opponent: [e62c6a3e-3123-4041-ab24-05382f85f23c](https://github.com/hampfh/hampfh/issues/51)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/b5c61daa-f9a0-4d34-8bca-0e279316f797.md)<br>[ERROR] Opponent: [f4e7e93d-fc25-4b64-9068-39506c1d7e9e](https://github.com/hampfh/hampfh/issues/52)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/0523bc8b-8120-4984-846e-fcf39714e15a.md)<br>[LOSS] Opponent: [bd8d0156-bd11-4ff9-b13c-b222d4abefa6](https://github.com/hampfh/hampfh/issues/26) &#124; [Match](../blob/live/data/matches/f6f7de7d-a442-43d6-bc80-7d0993f369fa.md)<br>[WIN] Opponent: [0f152710-dcbb-49df-8566-d82afaa2fd67](https://github.com/hampfh/hampfh/issues/27) &#124; [Match](../blob/live/data/matches/33c0a02f-7816-44e6-938c-238c2d3171fc.md)<br>

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [1da0638b-0912-4672-8237-4f5bf502c6b4](https://github.com/hampfh/hampfh/issues/55)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/4f1a3969-e2bb-4e06-b136-cc83ccce9b6b.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [adbd08b3-8504-4b72-83ae-23b843313692](https://github.com/hampfh/hampfh/issues/56)
**Error:**
Invalid move: Tile (4,1) is occupied


[Match](../blob/live/data/matches/d7664c0c-1b18-4db7-9391-e415e2e4ddf4.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [WIN] Opponent: [fe128b4c-b947-4420-990a-7658f8c2dc48](https://github.com/hampfh/hampfh/issues/61) &#124; [Match](../blob/live/data/matches/d50a7b5c-a0b9-4ecf-b5ce-49c99ebc71f0.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [e25da2fb-8bc8-4b19-b6af-69c5a64c6af9](https://github.com/hampfh/hampfh/issues/64)
**Error:**
Invalid move: Tile (4,7) is occupied


[Match](../blob/live/data/matches/018fe61f-f5fd-455a-8ca3-aeca9bad9cb7.md)

**Comment by hampfh** [comment]
[THIS MESSAGE IS AUTOMATIC]<br> [ERROR] Opponent: [6abd680d-558a-4d10-8a94-72ffccfa949c](https://github.com/hampfh/hampfh/issues/69)
**Error:**
Invalid move: Tile (4,8) is occupied


[Match](../blob/live/data/matches/cbaa3d7c-d812-4c04-afc7-8167d2e51478.md)
